-- 创建医药论坛文章表
CREATE TABLE IF NOT EXISTS `tcm_articles` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '文章ID',
  `title` VARCHAR(255) NOT NULL COMMENT '文章标题',
  `content` LONGTEXT NOT NULL COMMENT '文章内容',
  `user_id` BIGINT(20) NOT NULL COMMENT '作者ID',
  `category_id` BIGINT(20) NOT NULL COMMENT '板块ID',
  `tags` VARCHAR(255) DEFAULT NULL COMMENT '文章标签，用逗号分隔',
  `summary` VARCHAR(500) DEFAULT NULL COMMENT '文章摘要',
  `status` TINYINT(4) DEFAULT '1' COMMENT '状态：0-禁用，1-启用，2-审核中，3-审核失败',
  `view_count` INT(11) DEFAULT '0' COMMENT '阅读次数',
  `like_count` INT(11) DEFAULT '0' COMMENT '点赞次数',
  `comment_count` INT(11) DEFAULT '0' COMMENT '评论次数',
  `collect_count` INT(11) DEFAULT '0' COMMENT '收藏次数',
  `is_hot` TINYINT(1) DEFAULT '0' COMMENT '是否热门：0-否，1-是',
  `is_recommended` TINYINT(1) DEFAULT '0' COMMENT '是否推荐：0-否，1-是',
  `meta_keywords` VARCHAR(255) DEFAULT NULL COMMENT 'SEO关键字',
  `meta_description` VARCHAR(500) DEFAULT NULL COMMENT 'SEO描述',
  `source` VARCHAR(100) DEFAULT NULL COMMENT '文章来源',
  `author` VARCHAR(100) DEFAULT NULL COMMENT '文章作者（外部作者）',
  `cover_image` VARCHAR(255) DEFAULT NULL COMMENT '封面图片URL',
  `word_count` INT(11) DEFAULT '0' COMMENT '文章字数',
  `is_original` TINYINT(1) DEFAULT '1' COMMENT '是否原创：0-否，1-是',
  `original_url` VARCHAR(255) DEFAULT NULL COMMENT '原创文章URL（如果有）',
  `sort_order` INT(11) DEFAULT '0' COMMENT '排序字段',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` DATETIME DEFAULT NULL COMMENT '删除时间',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_category_id` (`category_id`),
  KEY `idx_status` (`status`),
  KEY `idx_is_hot` (`is_hot`),
  KEY `idx_is_recommended` (`is_recommended`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='医药论坛文章表';


